# Definitions file for the GNUCXX11_CEP4 compiler suite.
#
# $Id: GNUCXX11_CEP4.cmake 35708 2016-10-14 13:57:51Z jkuensem $


# Compiler suite
set(LOFAR_COMPILER_SUITES GNUCXX11_CEP4)

# Build variants
set(LOFAR_BUILD_VARIANTS DEBUG OPT OPT3 OPTARCH)

# GNU compiler suite
set(GNUCXX11_CEP4_COMPILERS GNUCXX11_CEP4_C GNUCXX11_CEP4_CXX GNUCXX11_CEP4_Fortran GNUCXX11_CEP4_ASM)
set(GNUCXX11_CEP4_C          gcc)      # GNU C compiler
set(GNUCXX11_CEP4_CXX        g++)       # GNU C+ compiler
set(GNUCXX11_CEP4_Fortran    gfortran) # GNU Fortran compiler
set(GNUCXX11_CEP4_ASM        gcc)      # GNU assembler

set(GNUCXX11_CEP4_C_FLAGS          "-W -Wall -Wno-unknown-pragmas")
set(GNUCXX11_CEP4_C_FLAGS_DEBUG    "-g")
set(GNUCXX11_CEP4_C_FLAGS_OPT      "-O2")
set(GNUCXX11_CEP4_C_FLAGS_OPT3     "-O3")
set(GNUCXX11_CEP4_C_FLAGS_OPTARCH  "-O3 -march=haswell")
set(GNUCXX11_CEP4_CXX_FLAGS        "-std=c++11 -W -Wall -Woverloaded-virtual -Wno-unknown-pragmas -D_GLIBCXX_USE_CXX11_ABI=1")
set(GNUCXX11_CEP4_CXX_FLAGS_DEBUG  "-g")
set(GNUCXX11_CEP4_CXX_FLAGS_OPT    "-O2")
set(GNUCXX11_CEP4_CXX_FLAGS_OPT3   "-O3")
set(GNUCXX11_CEP4_CXX_FLAGS_OPTARCH "-O3 -march=haswell")
set(GNUCXX11_CEP4_EXE_LINKER_FLAGS)
set(GNUCXX11_CEP4_EXE_LINKER_FLAGS_DEBUG)
set(GNUCXX11_CEP4_EXE_LINKER_FLAGS_OPT)
set(GNUCXX11_CEP4_EXE_LINKER_FLAGS_OPT3)
set(GNUCXX11_CEP4_EXE_LINKER_FLAGS_OPTARCH)
set(GNUCXX11_CEP4_SHARED_LINKER_FLAGS)
set(GNUCXX11_CEP4_SHARED_LINKER_FLAGS_DEBUG)
set(GNUCXX11_CEP4_SHARED_LINKER_FLAGS_OPT)
set(GNUCXX11_CEP4_SHARED_LINKER_FLAGS_OPT3)
set(GNUCXX11_CEP4_SHARED_LINKER_FLAGS_OPTARCH)
set(GNUCXX11_CEP4_COMPILE_DEFINITIONS)
set(GNUCXX11_CEP4_COMPILE_DEFINITIONS_DEBUG
                         "-DLOFAR_DEBUG -DENABLE_DBGASSERT -DENABLE_TRACER")
set(GNUCXX11_CEP4_COMPILE_DEFINITIONS_OPT)
set(GNUCXX11_CEP4_COMPILE_DEFINITIONS_OPT3
                         "-DNDEBUG -DDISABLE_DEBUG_OUTPUT")
set(GNUCXX11_CEP4_COMPILE_DEFINITIONS_OPTARCH
                         "-DNDEBUG -DDISABLE_DEBUG_OUTPUT")

