# Definitions file for the GNUCXX98 compiler suite.
#
# $Id: GNUCXX98.cmake 39875 2018-07-13 13:44:29Z loose $


# Compiler suite
set(LOFAR_COMPILER_SUITES GNUCXX98)

# Build variants
set(LOFAR_BUILD_VARIANTS DEBUG OPT OPT3 OPTARCH)

# GNUCXX98 compiler suite
set(GNUCXX98_COMPILERS GNUCXX98_C GNUCXX98_CXX GNUCXX98_Fortran GNUCXX98_ASM)
set(GNUCXX98_C         /usr/bin/gcc)      # GNUCXX98 C compiler
set(GNUCXX98_CXX       /usr/bin/g++)      # GNUCXX98 C++ compiler
set(GNUCXX98_Fortran   /usr/bin/gfortran) # GNUCXX98 Fortran compiler
set(GNUCXX98_ASM       /usr/bin/gcc)      # GNUCXX98 assembler

set(GNUCXX98_C_FLAGS          "-W -Wall -Wno-unknown-pragmas")
set(GNUCXX98_C_FLAGS_DEBUG    "-g")
set(GNUCXX98_C_FLAGS_OPT      "-g -O2")
set(GNUCXX98_C_FLAGS_OPT3     "-g -O3")
set(GNUCXX98_C_FLAGS_OPTARCH  "-g -O3 -march=native")
set(GNUCXX98_CXX_FLAGS        "-std=c++98 -W -Wall -Woverloaded-virtual -Wno-unknown-pragmas")
set(GNUCXX98_CXX_FLAGS_DEBUG  "-g")
set(GNUCXX98_CXX_FLAGS_OPT    "-g -O2")
set(GNUCXX98_CXX_FLAGS_OPT3   "-g -O3")
set(GNUCXX98_CXX_FLAGS_OPTARCH "-g -O3 -march=native")
set(GNUCXX98_EXE_LINKER_FLAGS)
set(GNUCXX98_EXE_LINKER_FLAGS_DEBUG)
set(GNUCXX98_EXE_LINKER_FLAGS_OPT)
set(GNUCXX98_EXE_LINKER_FLAGS_OPT3)
set(GNUCXX98_EXE_LINKER_FLAGS_OPTARCH)
set(GNUCXX98_SHARED_LINKER_FLAGS)
set(GNUCXX98_SHARED_LINKER_FLAGS_DEBUG)
set(GNUCXX98_SHARED_LINKER_FLAGS_OPT)
set(GNUCXX98_SHARED_LINKER_FLAGS_OPT3)
set(GNUCXX98_SHARED_LINKER_FLAGS_OPTARCH)
set(GNUCXX98_COMPILE_DEFINITIONS)
set(GNUCXX98_COMPILE_DEFINITIONS_DEBUG 
                         "-DLOFAR_DEBUG -DENABLE_DBGASSERT -DENABLE_TRACER")
set(GNUCXX98_COMPILE_DEFINITIONS_OPT)
set(GNUCXX98_COMPILE_DEFINITIONS_OPT3
                         "-DNDEBUG -DDISABLE_DEBUG_OUTPUT")
set(GNUCXX98_COMPILE_DEFINITIONS_OPTARCH
                         "-DNDEBUG -DDISABLE_DEBUG_OUTPUT")

