#!/usr/bin/env python3

'''
Simple utility to list or update RADB resource availability values.
Essentially a tool around RADB getResources(), updateResourceAvailability(),
  getResourceClaims() and (parts of) updateResourceClaims().
See the resourcetool.py module for more info.
'''

if __name__ == '__main__':
    from sys import argv, exit
    from lofar.sas.datamanagement.resourcetool.resourcetool import main
    exit(main(argv[1:]))
