#!/usr/bin/env python3
# $Id: momqueryservice 33373 2016-01-22 11:01:15Z schaap $

'''
runs the momqueryservice
'''

from lofar.mom.momqueryservice.momqueryservice import main

if __name__ == '__main__':
    main()
