CREATE DATABASE useradministration;
CREATE TABLE useradministration.useraccount ( id int(11) NOT NULL AUTO_INCREMENT, userid int(11) NOT NULL DEFAULT '0', username varchar(20) NOT NULL DEFAULT '', password varchar(32) NOT NULL DEFAULT '', publickey varchar(32) DEFAULT NULL, PRIMARY KEY (id), UNIQUE KEY useraccount_UNIQ (username) ) ENGINE=InnoDB AUTO_INCREMENT=1787 DEFAULT CHARSET=latin1;   
CREATE TABLE useradministration.useraccountsystemrole (id int(11) NOT NULL AUTO_INCREMENT, useraccountid int(11) NOT NULL DEFAULT '0', systemroleid int(11) NOT NULL DEFAULT '0', indexid int(11) NOT NULL DEFAULT '0', PRIMARY KEY (id), KEY useraccount_useraccountsystemrole_IND (useraccountid), KEY systemrole_useraccountsystemrole_IND (systemroleid), KEY useraccount_index_useraccountsystemrole_IND (indexid) ) ENGINE=InnoDB AUTO_INCREMENT=3413 DEFAULT CHARSET=latin1;
CREATE TABLE useradministration.user ( id int(11) NOT NULL AUTO_INCREMENT, title varchar(100) DEFAULT NULL, firstname varchar(100) DEFAULT NULL, lastname varchar(100) NOT NULL DEFAULT '', email varchar(100) DEFAULT NULL, phone1 varchar(100) DEFAULT NULL, phone2 varchar(100) DEFAULT NULL, fax varchar(100) DEFAULT NULL, PRIMARY KEY (id), KEY user_lastname_IND (lastname) ) ENGINE=InnoDB AUTO_INCREMENT=1790 DEFAULT CHARSET=latin1; 
# mom database
CREATE DATABASE mom; 
USE mom;
CREATE TABLE mom2objectstatus ( id int(11) NOT NULL AUTO_INCREMENT, name varchar(255) DEFAULT NULL, roles varchar(512) DEFAULT NULL, userid int(11) DEFAULT NULL, statusid int(11) DEFAULT NULL, mom2objectid int(11) DEFAULT NULL, indexid int(11) DEFAULT NULL, statustime datetime NOT NULL DEFAULT '1000-01-01 00:00:00.000000', pending tinyint(1) DEFAULT 0, PRIMARY KEY (id) ) ENGINE=InnoDB AUTO_INCREMENT=1725902 DEFAULT CHARSET=latin1;
CREATE TABLE mom2object (id int(11) NOT NULL AUTO_INCREMENT, parentid int(11) DEFAULT NULL, indexid int(11) DEFAULT NULL, mom2id int(11) NOT NULL DEFAULT 0, mom2objecttype char(25) NOT NULL, name varchar(100) NOT NULL DEFAULT '', description varchar(255) DEFAULT NULL, ownerprojectid int(11) DEFAULT NULL, currentstatusid int(11) DEFAULT NULL, topology varchar(100) DEFAULT NULL, predecessor varchar(512) DEFAULT NULL, topology_parent tinyint(1) DEFAULT 0, group_id int(11) DEFAULT 0, datasize bigint(20) DEFAULT 0, PRIMARY KEY (id), UNIQUE KEY mom2object_UNIQ (mom2id) ) ENGINE=InnoDB AUTO_INCREMENT=331855 DEFAULT CHARSET=latin1;
CREATE TABLE status (id int(11) NOT NULL AUTO_INCREMENT, code char(15) NOT NULL DEFAULT '', type char(20) NOT NULL, description varchar(100) DEFAULT NULL, PRIMARY KEY (id), UNIQUE KEY status_UNIQ (code,type) ) ENGINE=InnoDB AUTO_INCREMENT=712 DEFAULT CHARSET=latin1;
CREATE TABLE member ( id int(11) NOT NULL AUTO_INCREMENT, projectid int(11) DEFAULT NULL, indexid int(11) DEFAULT NULL, PRIMARY KEY (id), KEY mom2object_member_FK (projectid), KEY indexid_IND (indexid) ) ENGINE=InnoDB AUTO_INCREMENT=1010 DEFAULT CHARSET=latin1;
CREATE TABLE registeredmember ( id int(11) NOT NULL AUTO_INCREMENT, memberid int(11) DEFAULT NULL, userid int(11) DEFAULT NULL, PRIMARY KEY (id), KEY member_registeredmember_FK (memberid), KEY userid_IND (userid) ) ENGINE=InnoDB AUTO_INCREMENT=768 DEFAULT CHARSET=latin1;
CREATE TABLE memberprojectrole ( id int(11) NOT NULL AUTO_INCREMENT, memberid int(11) DEFAULT NULL, indexid int(11) DEFAULT NULL, projectroleid int(11) DEFAULT NULL, PRIMARY KEY (id), KEY member_memberprojectrole_FK (memberid), KEY projectrole_memberprojectrole_FK (projectroleid), KEY indexid_IND (indexid) ) ENGINE=InnoDB AUTO_INCREMENT=1167 DEFAULT CHARSET=latin1;
CREATE TABLE projectrole ( id int(11) NOT NULL AUTO_INCREMENT, name char(15) NOT NULL DEFAULT '', description varchar(100) DEFAULT NULL, PRIMARY KEY (id), UNIQUE KEY projectrole_UNIQ (name) ) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;
CREATE TABLE project ( id int(11) NOT NULL AUTO_INCREMENT, mom2objectid int(11) DEFAULT NULL, releasedate date DEFAULT NULL, PRIMARY KEY (id), KEY mom2object_IND (mom2objectid) ) ENGINE=InnoDB AUTO_INCREMENT=149 DEFAULT CHARSET=latin1;
ALTER TABLE project ADD allowtriggers BOOLEAN NOT NULL DEFAULT FALSE AFTER releasedate, ADD priority int(11) NOT NULL DEFAULT 1000 AFTER allowtriggers;
CREATE TABLE lofar_trigger ( id int(11) NOT NULL AUTO_INCREMENT, username varchar(120) NOT NULL DEFAULT '', hostname varchar(128) NOT NULL DEFAULT '', arrivaltime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, projectname varchar(100) NOT NULL DEFAULT '', metadata TEXT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (username) REFERENCES useradministration.useraccount(username)) ;
CREATE TABLE lofar_observation ( id int(11) NOT NULL AUTO_INCREMENT, mom2objectid int(11) DEFAULT NULL, observation_id int(11) DEFAULT NULL, instrument char(32) DEFAULT NULL, user_specification_id int(11) DEFAULT NULL, system_specification_id int(11) DEFAULT NULL,default_template varchar(50) DEFAULT NULL,tbb_template varchar(50) DEFAULT NULL,tbb_piggyback_allowed tinyint(1) DEFAULT '0',parset mediumtext,nr_output_correlated int(11) DEFAULT NULL,nr_output_beamformed int(11) DEFAULT NULL,nr_output_coherent_stokes int(11) DEFAULT NULL,nr_output_incoherent_stokes int(11) DEFAULT NULL,nr_output_flyseye int(11) DEFAULT NULL,nr_output_correlated_valid int(11) DEFAULT NULL,nr_output_beamformed_valid int(11) DEFAULT NULL,nr_output_coherent_stokes_valid int(11) DEFAULT NULL,nr_output_incoherent_stokes_valid int(11) DEFAULT NULL,nr_output_flyseye_valid int(11) DEFAULT NULL,feedback text,aartfaac_piggyback_allowed bit(1) DEFAULT b'1',storage_cluster_id int(11) DEFAULT NULL,processing_cluster_id int(11) DEFAULT NULL,nico_testing int(11) DEFAULT NULL,PRIMARY KEY (id),KEY lofar_observation_observation_id_IND (observation_id),KEY mom2object_lofar_observation_FK (mom2objectid),KEY user_specification_lofar_observation_FK (user_specification_id),KEY system_specification_lofar_observation_FK (system_specification_id)) ENGINE=InnoDB AUTO_INCREMENT=52874 DEFAULT CHARSET=latin1;
CREATE TABLE lofar_observation_specification (id int(11) NOT NULL AUTO_INCREMENT,type char(8) DEFAULT NULL,correlated_data tinyint(1) DEFAULT '1',filtered_data tinyint(1) DEFAULT '0',beamformed_data tinyint(1) DEFAULT '0',coherent_stokes_data tinyint(1) DEFAULT '0',incoherent_stokes_data tinyint(1) DEFAULT '0',antenna char(20) DEFAULT NULL,clock_mode char(10) DEFAULT NULL,instrument_filter char(15) DEFAULT NULL,integration_interval double DEFAULT NULL,channels_per_subband int(11) DEFAULT NULL,cn_integration_steps int(11) DEFAULT NULL,pencilbeams_flyseye tinyint(1) DEFAULT '0',pencilbeams_nr_pencil_rings int(11) DEFAULT NULL,pencilbeams_ring_size double DEFAULT NULL,stokes_selection char(4) DEFAULT NULL,stokes_integrate_channels tinyint(1) DEFAULT NULL,stokes_integration_steps int(11) unsigned DEFAULT NULL,station_set char(15) DEFAULT NULL,timeframe char(4) DEFAULT NULL,starttime datetime DEFAULT NULL,endtime datetime DEFAULT NULL,spec_duration double DEFAULT NULL,coherent_dedisperse_channels tinyint(1) DEFAULT '0',dispersion_measure float DEFAULT NULL,subbands_per_file_cs int(11) DEFAULT NULL,subbands_per_file_bf int(11) DEFAULT NULL,collapsed_channels_cs int(11) DEFAULT NULL,collapsed_channels_is int(11) DEFAULT NULL,downsampling_steps_cs int(11) DEFAULT NULL,downsampling_steps_is int(11) DEFAULT NULL,which_cs char(4) DEFAULT NULL,which_is char(4) DEFAULT NULL,bypass_pff tinyint(1) DEFAULT '0',enable_superterp tinyint(1) DEFAULT '0',flyseye tinyint(1) DEFAULT '0',tab_nr_rings int(11) DEFAULT NULL,tab_ring_size float DEFAULT NULL,bits_per_sample int(11) DEFAULT NULL,misc text,PRIMARY KEY (id),KEY lofar_observation_specification_type_IND (type)) ENGINE=InnoDB AUTO_INCREMENT=105645 DEFAULT CHARSET=latin1;
CREATE TABLE lofar_pipeline (id int(11) NOT NULL AUTO_INCREMENT,mom2objectid int(11) DEFAULT NULL,starttime datetime DEFAULT NULL,endtime datetime DEFAULT NULL,pipeline_id int(11) DEFAULT NULL,pending tinyint(1) DEFAULT '0',template varchar(100) DEFAULT NULL,runtimeDirectory varchar(255) DEFAULT NULL,resultDirectory varchar(255) DEFAULT NULL,workingDirectory varchar(255) DEFAULT NULL,parset longtext,nr_output_correlated int(11) DEFAULT NULL,nr_output_beamformed int(11) DEFAULT NULL,nr_output_instrument_model int(11) DEFAULT NULL,nr_output_skyimage int(11) DEFAULT NULL,nr_output_correlated_valid int(11) DEFAULT NULL,nr_output_beamformed_valid int(11) DEFAULT NULL,nr_output_instrument_model_valid int(11) DEFAULT NULL,nr_output_skyimage_valid int(11) DEFAULT NULL,feedback text,demixing_parameters_id int(11) DEFAULT NULL,bbs_parameters_id int(11) DEFAULT NULL,duration double DEFAULT NULL,storage_cluster_id int(11) DEFAULT NULL,processing_cluster_id int(11) DEFAULT NULL,misc text,PRIMARY KEY (id),KEY lofar_pipeline_pipeline_id_IND (pipeline_id),KEY mom2object_lofar_pipeline_FK (mom2objectid),KEY demixing_parameters_FK (demixing_parameters_id),KEY bbs_parameters_FK (bbs_parameters_id)) ENGINE=InnoDB AUTO_INCREMENT=75471 DEFAULT CHARSET=latin1;
# mom privilege
CREATE DATABASE momprivilege;
CREATE TABLE momprivilege.statustransitionrole ( id int(11) NOT NULL AUTO_INCREMENT, statustransitionid int(11) DEFAULT NULL, roleid int(11) NOT NULL, roletype char(100) NOT NULL, PRIMARY KEY (id), KEY roletype_IND (roleid,roletype), KEY statustransition_statustransitionrole_FK (statustransitionid) ) ENGINE=InnoDB AUTO_INCREMENT=8572 DEFAULT CHARSET=latin1;
CREATE TABLE momprivilege.statustransition (id int(11) NOT NULL AUTO_INCREMENT, oldstatusid int(11) NOT NULL, newstatusid int(11) NOT NULL, PRIMARY KEY (id), KEY oldstatus_IND (oldstatusid), KEY newstatus_IND (oldstatusid) ) ENGINE=InnoDB AUTO_INCREMENT=1272 DEFAULT CHARSET=latin1; 

