#
# This builds an image with all dependencies for the RTCP package based on the ci_base image
#
# base
#
FROM ci_base:latest

RUN echo "Installing packages for RTCP..." && \
    yum-config-manager --add-repo http://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-rhel7.repo && \
    yum -y install autogen  boost-python36-devel hdf5-devel blas-devel lapack-devel cfitsio-devel wcslib-devel ncurses-devel readline-devel fftw-devel libpqxx-devel unittest-cpp-devel numactl-devel openmpi-devel cuda && \
    pip3 install numpy

RUN echo "Installing Casacore..." && \
    git clone https://github.com/casacore/casacore && \
    mkdir /casacore/build/ && \
    cd /casacore/build/ && \
    cmake -DCMAKE_INSTALL_PREFIX=/opt/casacore -DBUILD_PYTHON3=ON -DBUILD_PYTHON=OFF -DPYTHON_EXECUTABLE=/usr/bin/python3 -DUSE_OPENMP=ON -DUSE_FFTW3=TRUE -DUSE_HDF5=ON -DCMAKE_BUILD_TYPE=Release .. && \
    make && \
    make install

RUN echo "Installing DAL..." && \
    git clone https://git.astron.nl/ro/dal2.git && \
    mkdir /DAL/build && \
    cd /DAL/build/ && \
    cmake -DCMAKE_INSTALL_PREFIX=/opt/DAL -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPYTHON_LIBRARY:FILEPATH=/usr/lib64/libpython3.6m.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m/ .. && \
    make && \
    make install



