#
# This builds an image with all dependencies for the LCU package based on the ci_base image
#
# base
#
FROM ci_base:latest

RUN echo "Installing packages for LCU..." && \
    yum -y install postgresql-devel && \
    pip3 install psycopg2 testing.postgresql lxml mock numpy
