#
# This builds an image with all dependencies for the QA package based on the ci_base image
#
# base
#
FROM ci_base:latest

RUN echo "Installing packages for QA..." && \
    yum -y install boost-python36-devel readline-devel postgresql-devel && \
    pip3 install kombu requests psycopg2 testing.postgresql