#
# base
#
FROM pulp:github-master

ENV INSTALLDIR /opt
USER 0
COPY ["sudoers", "/etc/"]

# Run-time dependencies
RUN apt-get update && apt-get install -y python-xmlrunner liblog4cplus-1.1-9 libxml2 libxml++2.6-2v5 openssh-client gettext-base rsync python-matplotlib
#
# *******************
#   QPID client
# *******************
#

ENV BOOST_VERSION=1.58

# Run-time dependencies
# QPID daemon legacy store would require: libaio1 libdb5.1++
RUN apt-get update && apt-get install -y sasl2-bin libuuid1 libnss3 libnspr4 xqilla libboost-program-options${BOOST_VERSION}.0 libboost-system${BOOST_VERSION}.0

# Install
# QPID daemon legacy store would require: libaio-dev libdb5.1++-dev
RUN apt-get update && apt-get install -y ruby ruby-dev libsasl2-dev uuid-dev libxerces-c-dev libnss3-dev libnspr4-dev help2man libsslcommon2-dev libxqilla-dev libboost-program-options${BOOST_VERSION}-dev libboost-filesystem${BOOST_VERSION}-dev && \
    mkdir ${INSTALLDIR}/qpid && \
    svn --non-interactive -q co https://svn.astron.nl/LOFAR/trunk/LCS/MessageBus/qpid/ ${INSTALLDIR}/qpid; \
    bash -c "HOME=/tmp ${INSTALLDIR}/qpid/local/sbin/build_qpid" && \
    bash -c "strip ${INSTALLDIR}/qpid/{bin,lib}/* || true" && \
    bash -c "rm -rf /tmp/sources" && \
    apt-get purge -y ruby ruby-dev libsasl2-dev uuid-dev libxerces-c-dev libnss3-dev libnspr4-dev help2man libsslcommon2-dev libxqilla-dev libboost-program-options${BOOST_VERSION}-dev libboost-filesystem${BOOST_VERSION}-dev && \
    apt-get autoremove -y

# *******************
#   Kombu client for Python
# *******************
RUN aptitude install -y python3-kombu

#
# *******************
#   LOFAR
# *******************
#

# Tell image build information
ENV LOFAR_BRANCH=${LOFAR_BRANCH_NAME} \
    LOFAR_TAG=${LOFAR_TAG} \
    LOFAR_REVISION=${LOFAR_REVISION} \
    LOFAR_BUILDVARIANT=gnucxx11_optarch

# Install
#some are already installed, but we need boost, and RUN apt-get update && apt-get install -y subversion cmake g++ gfortran bison flex liblog4cplus-dev libhdf5-dev libblitz0-dev python-dev libxml2-dev pkg-config libunittest++-dev libxml++2.6-dev binutils-dev && \
RUN apt-get update && apt-get install -y liblog4cplus-dev libhdf5-dev libblitz0-dev libunittest++-dev libxml++2.6-dev binutils-dev && \
    mkdir -p ${INSTALLDIR}/lofar/build/${LOFAR_BUILDVARIANT} && \
    cd ${INSTALLDIR}/lofar && \
    svn --non-interactive -q co -r ${LOFAR_REVISION} -N ${LOFAR_BRANCH_URL} src; \
    svn --non-interactive -q up src/CMake && \
    cd ${INSTALLDIR}/lofar/build/${LOFAR_BUILDVARIANT} && cmake -DBUILD_PACKAGES="Pipeline MessageBus OTDB_Services" -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=${INSTALLDIR}/lofar/ -DCASACORE_ROOT_DIR=${INSTALLDIR}/casacore/ -DQPID_ROOT_DIR=/opt/qpid/ -DUSE_OPENMP=True ${INSTALLDIR}/lofar/src/ && \
    cd ${INSTALLDIR}/lofar/build/${LOFAR_BUILDVARIANT} && make -j ${J} && \
    cd ${INSTALLDIR}/lofar/build/${LOFAR_BUILDVARIANT} && make install && \
    bash -c "mkdir -p ${INSTALLDIR}/lofar/var/{log,run}" && \
    bash -c "chmod a+rwx  ${INSTALLDIR}/lofar/var/{log,run}" && \
    bash -c "strip ${INSTALLDIR}/lofar/{bin,sbin,lib64}/* || true" && \
    bash -c "rm -rf ${INSTALLDIR}/lofar/{build,src}" && \
    apt-get purge -y liblog4cplus-dev libhdf5-dev libblitz0-dev libunittest++-dev libxml++2.6-dev binutils-dev && \
    apt-get autoremove -y

COPY ["bashrc", "/opt/"]
COPY ["chuser.sh", "/usr/local/bin"]
ENTRYPOINT ["/usr/local/bin/chuser.sh"]
