#!/bin/bash

# lofar
[ -r ${INSTALLDIR}/lofar/lofarinit.sh ] && source ${INSTALLDIR}/lofar/lofarinit.sh
export PATH PYTHONPATH LD_LIBRARY_PATH LOFARROOT

# qpid
#source ${INSTALLDIR}/qpid/.profile

# lofarsoft
echo "sourcing init"
source ${LOFARSOFT}/devel_common/scripts/init.sh

export PYTHONPATH=$PYTHONPATH:${LOFARSOFT}/release/lib/python/dal
export LD_LIBRARY_PATH=LD_LIBRARY_PATH:${LOFARSOFT}/release/lib
