#!/bin/sh

PATH=$(cd ../src && pwd):$PATH

getparsetvalue tgetparsetvalue.parset key1
getparsetvalue tgetparsetvalue.parset key1 0
getparsetvalue tgetparsetvalue.parset key1 1
getparsetvalue tgetparsetvalue.parset key1 2
getparsetvalue tgetparsetvalue.parset key1 3
getparsetvalue tgetparsetvalue.parset key1 -1
getparsetvalue tgetparsetvalue.parset key1 -2
getparsetvalue tgetparsetvalue.parset key1 -3
getparsetvalue tgetparsetvalue.parset key1 -4
getparsetvalue tgetparsetvalue.parset key1.sub1

getparsetvalue tgetparsetvalue.parset key0
getparsetvalue -d abc -d efgh tgetparsetvalue.parset key0
