#!/usr/bin/env python3
# $Id: taskprescheduler 33373 2016-01-22 11:01:15Z schaap $

'''
runs the task prescheduler service
'''
from lofar.sas.resourceassignment.taskprescheduler.taskprescheduler import main

if __name__ == '__main__':
    main()
